### ISSUE TITLE
Tutorial Error: `brown_clusters.txt` not found

### ISSUE THREAD

**Issue by JRMeyer** [snipsco/snips-nlu#582]
Hi All, 

I'm going through the tutorial <https://snips-nlu.readthedocs.io/en/latest/tutorial.html>, and there's a step which involves loading clusters from the Brown corpus, but the file `brown_clusters.txt` doesn't seem to exist.

I've installed `snips-nlu`, `Rust` and `rustsetup-tools` all from github or cURL in a virtualenv.

Ideas?

```
>>> import io
>>> import json
>>> 
>>> from snips_nlu import SnipsNLUEngine, load_resources
>>> from snips_nlu.default_configs import CONFIG_EN
>>> 
>>> load_resources(u"en")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/josh/git/snips-nlu/snips_nlu/resources.py", line 242, in load_resources
    _RESOURCES[language] = _load_resources(language)
  File "/home/josh/git/snips-nlu/snips_nlu/resources.py", line 225, in _load_resources
    resource = resource_fn(language)
  File "/home/josh/git/snips-nlu/snips_nlu/resources.py", line 134, in _load_clusters
    with io.open(path, encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/josh/git/snips-nlu/snips_nlu/snips-nlu-resources/en/brown_clusters.txt'
```

**Comment by adrienball** [comment]
Did you do a `pip install snips-nlu` at some point? There is a resources submodule which is fetched.

**Comment by JRMeyer** [comment]
I installed with pip via GitHub with something like:

`pip3 install git+https://github.com/snipsco/snips-nlu.git`

пн, 30 апр. 2018 г., 6:29 ПП Adrien Ball <notifications@github.com>:

**Comment by adrienball** [comment]
OK not sure about the behavior in that case regarding submodules. My guess is that submodules are not fetched and initiated when doing so. Can you try replacing this with `pip3 install snips-nlu`? 
I'm not on my laptop at the moment so can't really check that properly.

**Comment by JRMeyer** [comment]
I uninstalled and reinstalled with `pip3`:
```
(snips-nlu) josh@stealth:~$ pip3 install snips-nlu
Collecting snips-nlu
  Using cached https://files.pythonhosted.org/packages/46/f1/1b7753eddd986ee23915a75522d84857c8bc16b5e497506adbf0cb91d6fd/snips_nlu-0.13.3-py2.py3-none-any.whl
Requirement already satisfied: numpy==1.14.0 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (1.14.0)
Requirement already satisfied: snips-nlu-utils==0.6.1 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (0.6.1)
Requirement already satisfied: num2words==0.5.6 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (0.5.6)
Requirement already satisfied: sklearn-crfsuite==0.3.6 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (0.3.6)
Requirement already satisfied: scipy==1.0.0 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (1.0.0)
Requirement already satisfied: semantic-version==2.6.0 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (2.6.0)
Requirement already satisfied: snips-nlu-ontology==0.54.3 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (0.54.3)
Requirement already satisfied: pygments==2.2.0 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (2.2.0)
Requirement already satisfied: enum34==1.1.6 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (1.1.6)
Requirement already satisfied: scikit-learn==0.19.1 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu) (0.19.1)
Requirement already satisfied: future==0.16.0 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu-utils==0.6.1->snips-nlu) (0.16.0)
Requirement already satisfied: six in ./envs/snips-nlu/lib/python3.6/site-packages (from sklearn-crfsuite==0.3.6->snips-nlu) (1.11.0)
Requirement already satisfied: python-crfsuite>=0.8.3 in ./envs/snips-nlu/lib/python3.6/site-packages (from sklearn-crfsuite==0.3.6->snips-nlu) (0.9.5)
Requirement already satisfied: tqdm>=2.0 in ./envs/snips-nlu/lib/python3.6/site-packages (from sklearn-crfsuite==0.3.6->snips-nlu) (4.23.1)
Requirement already satisfied: tabulate in ./envs/snips-nlu/lib/python3.6/site-packages (from sklearn-crfsuite==0.3.6->snips-nlu) (0.8.2)
Requirement already satisfied: wheel==0.30.0 in ./envs/snips-nlu/lib/python3.6/site-packages (from snips-nlu-ontology==0.54.3->snips-nlu) (0.30.0)
Installing collected packages: snips-nlu
Successfully installed snips-nlu-0.13.3
```

but I get the same error as above:/

**Comment by adrienball** [comment]
What is your version of `pip3` (`pip3 --version`) ?

Can you try the following:
- Upgrade pip --> `pip3 install --upgrade pip`
- uninstall `snips-nlu`
- Remove `/home/josh/git/snips-nlu` directory if it still exists
- install snips-nlu with `pip3 install snips-nlu==0.13.3`
- Run your script

**Comment by JRMeyer** [comment]
Hi Adrien, 

I did exactly what you said, in exact order, and now it works:)

I had different versions of `pip3` for my global system and for 
my `snips` env I made with `virtual-env`. My env `pip3` was up-to-date
but I might have installed `snips-nlu` with the former.

In any case, it works... thanks for the help!
