### ISSUE TITLE
error while fitting engine on custom dataset with multiple entites

### ISSUE THREAD

**Issue by rohan7797** [snipsco/snips-nlu#618]
Hi 
I'm using snips on windows10 anaconda 
I followed the tutorial but tried to generate my own dataset with multiple entities using the command given
and while fitting the data i got this error
OSError                                   Traceback (most recent call last)
<ipython-input-55-0ef1ad4bb99b> in <module>()
      1 with io.open("dataset45.json") as f:
      2     dataset = json.load(f)
----> 3 engine.fit(dataset)

~\Anaconda3\lib\site-packages\snips_nlu\utils.py in wrapped(*args, **kwargs)
    254             start = datetime.now()
    255             msg_fmt = dict()
--> 256             res = fn(*args, **kwargs)
    257             if "elapsed_time" in output_msg:
    258                 msg_fmt["elapsed_time"] = datetime.now() - start

~\Anaconda3\lib\site-packages\snips_nlu\nlu_engine\nlu_engine.py in fit(self, dataset, force_retrain)
     93                 recycled_parser = build_processing_unit(parser_config)
     94             if force_retrain or not recycled_parser.fitted:
---> 95                 recycled_parser.fit(dataset, force_retrain)
     96             parsers.append(recycled_parser)
     97 

~\Anaconda3\lib\site-packages\snips_nlu\utils.py in wrapped(*args, **kwargs)
    254             start = datetime.now()
    255             msg_fmt = dict()
--> 256             res = fn(*args, **kwargs)
    257             if "elapsed_time" in output_msg:
    258                 msg_fmt["elapsed_time"] = datetime.now() - start

~\Anaconda3\lib\site-packages\snips_nlu\intent_parser\probabilistic_intent_parser.py in fit(self, dataset, force_retrain)
     82                     slot_filler_config)
     83             if force_retrain or not self.slot_fillers[intent_name].fitted:
---> 84                 self.slot_fillers[intent_name].fit(dataset, intent_name)
     85         logger.debug("Fitted slot fillers in %s",
     86                      elapsed_since(slot_fillers_start))

~\Anaconda3\lib\site-packages\snips_nlu\utils.py in wrapped(*args, **kwargs)
    254             start = datetime.now()
    255             msg_fmt = dict()
--> 256             res = fn(*args, **kwargs)
    257             if "elapsed_time" in output_msg:
    258                 msg_fmt["elapsed_time"] = datetime.now() - start

~\Anaconda3\lib\site-packages\snips_nlu\slot_filler\crf_slot_filler.py in fit(self, dataset, intent)
    130         # pylint: disable=C0103
    131         X = [self.compute_features(sample[TOKENS], drop_out=True)
--> 132              for sample in crf_samples]
    133         # ensure ascii tags
    134         Y = [[_encode_tag(tag) for tag in sample[TAGS]]

~\Anaconda3\lib\site-packages\snips_nlu\slot_filler\crf_slot_filler.py in <listcomp>(.0)
    130         # pylint: disable=C0103
    131         X = [self.compute_features(sample[TOKENS], drop_out=True)
--> 132              for sample in crf_samples]
    133         # ensure ascii tags
    134         Y = [[_encode_tag(tag) for tag in sample[TAGS]]

~\Anaconda3\lib\site-packages\snips_nlu\slot_filler\crf_slot_filler.py in compute_features(self, tokens, drop_out)
    200                 if drop_out and random_state.rand() < f_drop_out:
    201                     continue
--> 202                 value = feature.compute(i, cache)
    203                 if value is not None:
    204                     token_features[feature.name] = value

~\Anaconda3\lib\site-packages\snips_nlu\slot_filler\feature.py in compute(self, token_index, cache)
     57 
     58         tokens = [c["token"] for c in cache]
---> 59         value = self.function(tokens, token_index + self.offset)
     60         cache[token_index + self.offset][self.base_name] = value
     61         return value

~\Anaconda3\lib\site-packages\snips_nlu\slot_filler\feature_factory.py in builtin_entity_match(tokens, token_index)
    494 
    495             builtin_entities = get_builtin_entities(
--> 496                 text, self.language, scope=[builtin_entity], use_cache=True)
    497             builtin_entities = [ent for ent in builtin_entities
    498                                 if entity_filter(ent, start, end)]

~\Anaconda3\lib\site-packages\snips_nlu\builtin_entities.py in get_builtin_entities(text, language, scope, use_cache)
     44 def get_builtin_entities(text, language, scope=None, use_cache=True):
     45     parser = get_builtin_entity_parser(language)
---> 46     return parser.parse(text, scope=scope, use_cache=use_cache)
     47 
     48 

~\Anaconda3\lib\site-packages\snips_nlu\builtin_entities.py in parse(self, text, scope, use_cache)
     24         cache_key = (text, str(scope))
     25         if cache_key not in self._cache:
---> 26             parser_result = self.parser.parse(text, scope)
     27             self._cache[cache_key] = parser_result
     28         return self._cache[cache_key]

~\Anaconda3\lib\site-packages\snips_nlu_ontology\builtin_entities.py in parse(self, text, scope)
    157         with string_pointer(c_char_p()) as ptr:
    158             exit_code = lib.snips_nlu_ontology_extract_entities_json(
--> 159                 self._parser, text.encode("utf8"), scope, byref(ptr))
    160             if exit_code:
    161                 raise ValueError("Something wrong happened while extracting "

OSError: [WinError -1073741795] Windows Error 0xc000001d

snips-nlu generate-dataset en intent_Lan.txt intent_ot.txt intent_reset.txt entity_LanID.txt entity_otp.txt entity_PasswordReset.txt > dataset.json

my .txt files were
[intent_ot.txt](https://github.com/snipsco/snips-nlu/files/2173743/intent_ot.txt)
[intent_reset.txt](https://github.com/snipsco/snips-nlu/files/2173744/intent_reset.txt)
[entity_ResetPassword.txt](https://github.com/snipsco/snips-nlu/files/2173745/entity_ResetPassword.txt)
[intent_Lan.txt](https://github.com/snipsco/snips-nlu/files/2173746/intent_Lan.txt)
[entity_LanID.txt](https://github.com/snipsco/snips-nlu/files/2173748/entity_LanID.txt)
[entity_otp.txt](https://github.com/snipsco/snips-nlu/files/2173753/entity_otp.txt)

**Comment by adrienball** [comment]
Hey @rohan7797 ,
I believe this issue is the same as https://github.com/snipsco/snips-nlu/issues/605, in which case a fix will be available soon (next week).
Leaving it open, as this has to be confirmed.

Thanks for reporting it!
Cheers

**Comment by rohan7797** [comment]
Thanks for the quick response the snips engine and documentation are very helpful. Looking forward to the next release

**Comment by adrienball** [comment]
Hey @rohan7797,
As mentioned in #605 , a new version of snips-nlu (0.15.1) is available on pypi. Can you try to upgrade and check if you still run into the issue?
Cheers

**Comment by rohan7797** [comment]
Yes will do that asap and get back to you
Thanks for the quick response
Rohan

**Comment by jy6666666** [comment]
Hi, I think I still have the same problem after I upgrading the version, current version is 0.15.1.
the dataset i used is from the tutorial [here](https://snips-nlu.readthedocs.io/en/latest/tutorial.html). 
I used sample_dataset=cli.generate_dataset('en','intent_turnLightOn.txt','intent_turnLightOff.txt','intent_setTemperature.txt','entity_room.txt') 
i modified the  **cli.generate_datase()** so this will return a dictionary which should be fine to be used in nlu_engine.fit(sample_dataset), right??

when i run nlu_engine.fit(sample_dataset), i got error:
Traceback (most recent call last):
  File "D:/Pycharm/PyCharm 2018.1.4/test/test.py", line 20, in <module>
    nlu_engine.fit(data)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\utils.py", line 256, in wrapped
    res = fn(*args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\nlu_engine\nlu_engine.py", line 95, in fit
    recycled_parser.fit(dataset, force_retrain)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\utils.py", line 256, in wrapped
    res = fn(*args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\intent_parser\probabilistic_intent_parser.py", line 84, in fit
    self.slot_fillers[intent_name].fit(dataset, intent_name)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\utils.py", line 256, in wrapped
    res = fn(*args, **kwargs)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\slot_filler\crf_slot_filler.py", line 132, in fit
    for sample in crf_samples]
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\slot_filler\crf_slot_filler.py", line 132, in <listcomp>
    for sample in crf_samples]
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\slot_filler\crf_slot_filler.py", line 202, in compute_features
    value = feature.compute(i, cache)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\slot_filler\feature.py", line 59, in compute
    value = self.function(tokens, token_index + self.offset)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\slot_filler\feature_factory.py", line 496, in builtin_entity_match
    text, self.language, scope=[builtin_entity], use_cache=True)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\builtin_entities.py", line 46, in get_builtin_entities
    return parser.parse(text, scope=scope, use_cache=use_cache)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu\builtin_entities.py", line 26, in parse
    parser_result = self.parser.parse(text, scope)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python36-32\lib\site-packages\snips_nlu_ontology\builtin_entities.py", line 159, in parse
    self._parser, text.encode("utf8"), scope, byref(ptr))
OSError: [WinError -529697949] Windows Error 0xe06d7363

**Comment by jy6666666** [comment]
hey @adrienball ,just ignore my last post first, my snips-nlu was not successfully updated, I will let you know once I tried on 0.15.1 version. my current version is actually 0.15.0

**Comment by jy6666666** [comment]
@adrienball , hey adrienball, I have updated my version to 0.15.1 and successfully run the tutorial exercise in Anaconda, so I think it has been fixed.

cheers

**Comment by adrienball** [comment]
Hey @rohan7797, I'm closing this issue as your last update was one month ago.
Feel free to re-open if you still have troubles.
Cheers
