### ISSUE TITLE
Installation issue on "aarch64 GNU/Linux" 

### ISSUE THREAD

**Issue by ak-nv** [snipsco/snips-nlu#756]
According to instructions, I installed setuptools_rust and rust 

$python3 -V
Python 3.6.7

setuptools_rust were installed by 
$python3 -m pip install setuptools_rust
It gives me output as, Installing collected packages: toml, semantic-version, setuptools-rust
Successfully installed semantic-version-2.6.0 setuptools-rust-0.10.6 toml-0.10.0

$ rustc --version
rustc 1.32.0 (9fda7c223 2019-01-16)

However when I try setting up snips-nlu using following instruction:
$python3 -m pip install snips-nlu

Collecting snips-nlu
  Using cached https://files.pythonhosted.org/packages/2e/d5/a928f703640f69992277f95f2b95075e7f3f02e9199ef253d9d78a9c6e2b/snips_nlu-0.19.2-py2.py3-none-any.whl
Collecting semantic-version<3.0,>=2.6 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/28/be/3a7241d731ba89063780279a5433f5971c1cf41735b64a9f874b7c3ff995/semantic_version-2.6.0-py3-none-any.whl
Collecting pyaml<18,>=17 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/17/c1/5892f756109e54ed53c753129b0da4acf6b6add8dff5a85b18667553b16d/pyaml-17.12.1-py2.py3-none-any.whl
Collecting plac<1.0,>=0.9.6 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
Collecting numpy<1.16,>=1.15 (from snips-nlu)
Collecting future<0.17,>=0.16 (from snips-nlu)
Collecting sklearn-crfsuite<0.4,>=0.3.6 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/25/74/5b7befa513482e6dee1f3dd68171a6c9dfc14c0eaa00f885ffeba54fe9b0/sklearn_crfsuite-0.3.6-py2.py3-none-any.whl
Collecting snips-nlu-parsers<0.2,>=0.1 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/c5/b3/c4e2060b11df89d70e782b368557db0fe7af656115c54702b120750dc0a2/snips_nlu_parsers-0.1.2.tar.gz
Collecting num2words<0.6,>=0.5.6 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/97/59/daea20448b3bf3cc07694f393a2a9d06439e4c9a96f83734d9d2c5231703/num2words-0.5.9-py3-none-any.whl
Collecting deprecation<3,>=2 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/32/e9/01ffbaf3540ad54476cd7066439d629f1dd73b851cc5c0993ce2c12e1cdd/deprecation-2.0.6-py2.py3-none-any.whl
Collecting snips-nlu-utils<0.8,>=0.7 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/75/54/2b6aa49f784f6bc470a6d45bd4c9ae9ffe673b5be6b556c1ef42f30aee17/snips_nlu_utils-0.7.1.tar.gz
Collecting scipy<2.0,>=1.0 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/a9/b4/5598a706697d1e2929eaf7fe68898ef4bea76e4950b9efbe1ef396b8813a/scipy-1.2.1.tar.gz
Collecting requests<3.0,>=2.0 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting scikit-learn<0.20,>=0.19 (from snips-nlu)
  Using cached https://files.pythonhosted.org/packages/25/b6/454cf208be93efa3db50ce06b732328c57ede005d1dcfa71d9a1548530b0/scikit-learn-0.19.2.tar.gz
Collecting PyYAML (from pyaml<18,>=17->snips-nlu)
Collecting six (from sklearn-crfsuite<0.4,>=0.3.6->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tqdm>=2.0 (from sklearn-crfsuite<0.4,>=0.3.6->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl
Collecting python-crfsuite>=0.8.3 (from sklearn-crfsuite<0.4,>=0.3.6->snips-nlu)
Collecting tabulate (from sklearn-crfsuite<0.4,>=0.3.6->snips-nlu)
Collecting docopt>=0.6.2 (from num2words<0.6,>=0.5.6->snips-nlu)
Collecting packaging (from deprecation<3,>=2->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests<3.0,>=2.0->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests<3.0,>=2.0->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0,>=2.0->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0,>=2.0->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->deprecation<3,>=2->snips-nlu)
  Using cached https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl
Building wheels for collected packages: snips-nlu-parsers, snips-nlu-utils, scipy, scikit-learn
  Running setup.py bdist_wheel for snips-nlu-parsers ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3k63cejl/snips-nlu-parsers/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpu7h4di4ppip-wheel- --python-tag cp36:
  /usr/lib/python3/dist-packages/setuptools/dist.py:397: UserWarning: Normalizing'0.1.2
  ' to '0.1.2'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/snips_nlu_parsers
  copying snips_nlu_parsers/builtin_entities.py -> build/lib/snips_nlu_parsers
  copying snips_nlu_parsers/gazetteer_entity_parser.py -> build/lib/snips_nlu_parsers
  copying snips_nlu_parsers/utils.py -> build/lib/snips_nlu_parsers
  copying snips_nlu_parsers/__init__.py -> build/lib/snips_nlu_parsers
  copying snips_nlu_parsers/builtin_entity_parser.py -> build/lib/snips_nlu_parsers
  running egg_info
  writing snips_nlu_parsers.egg-info/PKG-INFO
  writing dependency_links to snips_nlu_parsers.egg-info/dependency_links.txt
  writing requirements to snips_nlu_parsers.egg-info/requires.txt
  writing top-level names to snips_nlu_parsers.egg-info/top_level.txt
  reading manifest file 'snips_nlu_parsers.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '*' found under directory 'ffi/target/'
  warning: no previously-included files matching '__pycache__' found anywhere in distribution
  warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
  writing manifest file 'snips_nlu_parsers.egg-info/SOURCES.txt'
  copying snips_nlu_parsers/__version__ -> build/lib/snips_nlu_parsers
  creating build/lib/snips_nlu_parsers/dylib
  copying snips_nlu_parsers/dylib/.gitignore -> build/lib/snips_nlu_parsers/dylib
  running build_ext
  running build_rust
      Updating crates.io index
      Updating git repository `https://github.com/snipsco/snips-utils-rs`
      Updating git repository `https://github.com/snipsco/snips-nlu-ontology`
      Updating git repository `https://github.com/snipsco/snips-nlu-parsers`
      Updating git repository `https://github.com/snipsco/gazetteer-entity-parser`
      Updating git repository `https://github.com/snipsco/rustling-ontology`
      Updating git repository `https://github.com/snipsco/snips-nlu-utils`
      Updating git repository `https://github.com/snipsco/rustling`
   Downloading crates ...
    Downloaded rustc-demangle v0.1.13
    Downloaded cc v1.0.29
    Downloaded winapi v0.3.6
    Downloaded vec_map v0.8.1
    Downloaded num-traits v0.1.43
    Downloaded winapi-i686-pc-windows-gnu v0.4.0
  error: failed to unpack package `winapi-i686-pc-windows-gnu v0.4.0`

  Caused by:
    failed to unpack entry at `winapi-i686-pc-windows-gnu-0.4.0/lib/libwinapi_onecoreuap-api-ms-win-core-url-l1-1-0.a`

  Caused by:
    failed to unpack `/home/nvidia/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-i686-pc-windows-gnu-0.4.0/lib/libwinapi_onecoreuap-api-ms-win-core-url-l1-1-0.a`
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-3k63cejl/snips-nlu-parsers/setup.py", line 60, in <module>
      zip_safe=False)
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools_rust/build_ext.py", line 26, in run
      build_rust.run()
    File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools_rust/build.py", line 313, in run
      self.build_extension(ext)
    File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools_rust/build.py", line 95, in build_extension
      metadata = json.loads(check_output(metadata_command).decode("utf-8"))
    File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.6/subprocess.py", line 418, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'ffi/Cargo.toml', '--format-version', '1']' returned non-zero exit status 101.

  ----------------------------------------
  Failed building wheel for snips-nlu-parsers

**Comment by ClemDoum** [comment]
Hi @ak-nv sorry for the late reply.
I'm looking at your issue, we'll come back to you shortly.

**Comment by adrienball** [comment]
Hey @ak-nv ,
Can you confirm that you have enough space left on your device?
Thanks

**Comment by ak-nv** [comment]
@adrienball I have about 16GB space on my device.

**Comment by ak-nv** [comment]
@ClemDoum and @adrienball Any updates on this? I would like to test out on my Jetson board. Please let me know.

**Comment by adrienball** [comment]
@ak-nv,
It's quite hard to debug this issue on our side as we cannot reproduce your build environment (no Jetson board here), and the stacktrace suggests that the issues is not directly linked to `snips-nlu-rs`. Have you tried to build other rust crates on your board?

**Comment by adrienball** [comment]
Also, latest rust version is now 1.34.1 so it may be worth updating.
