### ISSUE TITLE
CLI "generate-dataset" crashes for text file input

### ISSUE THREAD

**Issue by dellison** [snipsco/snips-nlu#802]
It look like `Dataset.from_files` was removed from `Dataset` (and the documentation and stuff) but not from the CLI, which results in an ugly crash when calling `snips-nlu generate-dataset on text files`. For example:

```
$ snips-nlu generate-dataset en intent_a.txt intent_b.txt ...
Traceback (most recent call last):
  File "c:\users\davide\anaconda3\envs\snips\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\davide\anaconda3\envs\snips\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\davide\anaconda3\envs\snips\Scripts\snips-nlu.exe\__main__.py", line 9, in <module>
  File "c:\users\davide\anaconda3\envs\snips\lib\site-packages\snips_nlu\__main__.py", line 39, in main
    plac.call(commands[command], sys.argv[1:])
  File "c:\users\davide\anaconda3\envs\snips\lib\site-packages\plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "c:\users\davide\anaconda3\envs\snips\lib\site-packages\plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "c:\users\davide\anaconda3\envs\snips\lib\site-packages\snips_nlu\cli\generate_dataset.py", line 19, in generate_dataset
    dataset = Dataset.from_files(language, list(files))
AttributeError: type object 'Dataset' has no attribute 'from_files'
```

I'm on version 0.19.6, but I see the problem in the current code:
https://github.com/snipsco/snips-nlu/blob/develop/snips_nlu/cli/generate_dataset.py#L19
https://github.com/snipsco/snips-nlu/blob/develop/snips_nlu/dataset/dataset.py

Looks like this was introduced here: https://github.com/snipsco/snips-nlu/commit/e947b01c8551d00dd7997486031257ca7d9f62fd#diff-959b7a14a26980e7ddc1079982c1e7a0

**Comment by adrienball** [comment]
Hi @dellison ,
Good catch indeed, I've fixed this in #803 .
Thanks!
