### ISSUE TITLE
No module named 'setuptools_rust' on Win 11 x64

### ISSUE THREAD

**Issue by navix14** [snipsco/snips-nlu#909]
**Question**
I am trying to install the `snips-nlu` package on a Windows 11 machine. After executing `pip install snips-nlu` it fails with the following error:

```bash
× Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-i_5j4f12\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-i_5j4f12\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-i_5j4f12\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-i_5j4f12\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'setuptools_rust'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```

**Specs**
- Windows 11 x64 21H2 (Build 22000.1817)
- Python 3.11.3
- pip 23.1.2
- rustc 1.69.0
- cargo 1.69.0

**Steps to reproduce**
1. `python -m venv example`
2. `.\example\Scripts\activate.bat`
3. `pip install --upgrade pip`
4. `pip install setuptools_rust`
```
(example) λ pip list
Package           Version
----------------- -------
pip               23.1.2
semantic-version  2.10.0
setuptools        65.5.0
setuptools-rust   1.6.0
typing_extensions 4.5.0
```
6. `pip install snips-nlu`

I tried the same steps without using a virtual environment with a clean Python 3.11.3, Python 3.9 & Python 3.8.9 installation. Unfortunately, same result :(

**Comment by tazz4843** [comment]
Getting this on Arch Linux using Python 3.11.3 as well. Ran `python3 -m pip install setuptools-rust` after which I got a unrelated error. Hopefully this helps someone in the future. Do keep in mind this repo looks abandoned now, so that might be another issue for the future.
